### PR TITLE
use the actual distance instead of the squared distance to determine if the origin is on the facet of the simplex.

### PR DESCRIPTION
**Pull request by hongkai-dai**
cc @avalenzu

---
This change is [Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/365)

### CODE REVIEW

**Comment by sherm1** [comment]
I'm confirming that the CI failure is only the test_fcl_distance tolerance problem that we've been seeing on Macs, unrelated to this PR.

**Comment by SeanCurtis-TRI** [comment]
The mac test hasn't failed in ages? Why did it suddenly start failing now?

**Comment by hongkai-dai** [comment]
The last PR https://github.com/flexible-collision-library/fcl/pull/362 merged before this one also has the same mac test failure.

**Comment by SeanCurtis-TRI** [comment]
So, in November (#352) was the last PR that was about math. That passed (and several prior to that). Then we had a couple of CMake-related PRs that failed. Weird that that's come back.

**Comment by sherm1** [comment]
From looking at the closed-PR list it appears that #360 was the first one that failed. That did include some small Mac-only CMake changes. Hard to see how that would break anything though -- any thoughts @jamiesnape ?

**Comment by jamiesnape** [comment]
Not related. Master actually failed before then.

**Comment by SeanCurtis-TRI** [comment]
Precisely - it's the same mac error we've been getting since  January 16 (https://travis-ci.org/flexible-collision-library/fcl/builds/480449098). That is *not* the failure we were consistently getting all of last year where we'd confirm it was the "known failure" and merge anyways.

This is failure in a very specific test -- one related to #293. It requires a box-box distance test to be evaluated with GJK. Curiously, the expected answer and computed answer differ by 10^-7 which feels very theshold-ish; but I'm not sure what would cause a change in behavior. I'll post an issue.

**Comment by jamiesnape** [comment]
> I'll post an issue.

#361 is not that issue?

**Comment by SeanCurtis-TRI** [comment]
@jamiesnape you are 100% right. I've assigned myself to that issue. Thanks.

**Pull request merged**
