### PR TITLE
Do not use cache variables to construct fcl.h header

### LINKED ISSUE #303: cmake 3.11 adds "new line" warning
```
CMake Warning:
  Value of fcl_headers contained a newline; truncating
```

Needs a fix in the `FCLMacros.cmake` as now these two lines are `CMakeCache.txt`

```
CMakeCache.txt:fcl_headers:INTERNAL=#include "fcl/config.h"
CMakeCache.txt:# WARNING: Value of fcl_headers contained a newline and was truncated.
```

### LINKED ISSUE #433: CMake Warning:
Is Any body meet this error when you compile the FcL,How to slove it??
CMake Warning:
  Value of fcl_headers contained a newline; truncating

### PR DESCRIPTION
**Pull request by jamiesnape**
Also fix up installation of headers that was tied into the header generation. Fixes #303. Closes #432. Fixes #433.

Note that using `file(GLOB)` and `file(GLOB_RECURSE)` for source files is very much frowned upon, since CMake does not know whether to regenerate build files if no CMake file is edited, but that is what has been used here as long as the git history shows, so I am not addressing that in this fix.

---
This change is [Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/363)

### CODE REVIEW

**Comment by jamiesnape** [comment]
Windows is not happy.

**Comment by sherm1** [comment]
Odd -- AppVeyor completed successfully as did all Travis tests but GitHub thinks Travis isn't done.

**Comment by sherm1** [comment]
@jamiesnape here's the fcl.h diff I got on Ubuntu using CMake 3.10.2:
```
< NEW
> OLD
5d4
<  *  Copyright (c) 2020, Toyota Research Institute, Inc.
18c17
<  *   * Neither the name of the copyright holder nor the names of its
---
>  *   * Neither the name of Open Source Robotics Foundation nor the names of its
38c37
< // GENERATED FILE DO NOT EDIT.
---
> // Automatically generated file by cmake
40,41c39,40
< #ifndef FCL_FCL_H_
< #define FCL_FCL_H_
---
> #ifndef FCL_FCL_H
> #define FCL_FCL_H
44d42
< #include "fcl/export.h"
132c130,131
< #endif  // FCL_FCL_H_
---
> 
> #endif
```

The only substantive change I see there is the addition of `fcl/export.h`. Is that what you expected?
The build and install went smoothly on Ubuntu with Octree enabled and all tests passed. There were a few compiler warnings.

**Comment by jslee02** [comment]
Maybe you could add a simple example project that uses installed FCL. [This](https://github.com/dartsim/dart/blob/master/.ci/script.sh#L116-L133) is what DART does.

**Comment by jamiesnape** [comment]
The asymptotic nature of continuous integration and delivery....

**Pull request merged**
