### PR TITLE
Use Eigen for math operations

### PR DESCRIPTION
**Pull request by jslee02**
This PR switches to Eigen for the math operations as suggested (#96).

The goal of this PR is to pass all the unit tests with equal to or better than the previous computational performance, and it seems it's achieved as of now. Other possible improvements (e.g., the templatizing suggested by @sherm1 ([comment](https://github.com/flexible-collision-library/fcl/issues/96#issuecomment-234699398))) might be done in a separate PR.

~~Here are several todos that will be done in this PR:~~
- ~~removing repetitive conversion between quaternion and rotation matrix~~
- ~~[utilizing lazy evaluation](https://eigen.tuxfamily.org/dox/TopicLazyEvaluation.html)~~
- ~~[utilizing aliasing](https://eigen.tuxfamily.org/dox/group__TopicAliasing.html)~~

Edit: Above todos will be done in future PRs to keep this PR as simple as possible for code review.

### CODE REVIEW

**Comment by traversaro** [comment]
Some minor comments on the CMake parts of this PR, that can be probably fixed in other PRs . 
* There is any specific reason to use a custom pkg-config based `FindEIGEN3.cmake` rather then to copy `FindEigen3.cmake` officially distributed by Eigen [1]? I always had bad experience in using `pkg-config` in Windows, especially regarding path with spaces. I also suggest to integration the modification proposed in this PR [2], so if there is a `Eigen3Config.cmake` available in the system we use the information provided by that one. 

* The Eigen3 headers directories are include at directory level with a `#include_directories(${EIGEN3_INCLUDE_DIRS})`, but given that Eigen3 headers are include in the public headers, we need to populate the `INTERFACE_INCLUDE_DIRECTORIES` of the exported `fcl` target. We can do that by calling `target_include_directories(fcl PUBLIC ${EIGEN3_INCLUDE_DIRS})`. Note that this will result in a non-relocatable `fclConfig.cmake`, but this can be solved in future PRs I think. 

[1] : https://bitbucket.org/eigen/eigen/src/8267656b597c03c7fe501be33056cda9a63e88ab/cmake/FindEigen3.cmake?at=default&fileviewer=file-view-default
[2] : https://bitbucket.org/eigen/eigen/pull-requests/213/modify-findeigen3cmake-to-find/diff

**Comment by jslee02** [comment]
Thanks for the comments! I just didn't know that there is an officially distributed `FindEigen3.cmake`. Could we apply the proposed modification once it gets merged, though? Just in case it's updated with some feedbacks.

**Comment by traversaro** [comment]
Yes, it make sense to adopt the changes in `FindEigen3.cmake` only when they are adopted upstream.

**Comment by sherm1** [comment]
Eigen conversion looks great, @jslee02. Very nice to see files get deleted!

**Comment by peterkty** [comment]
Just a note that
setQuatRotation(), setTranslation() for transformation are no longer available after the conversion.
Transform3f was a quaternion plus translation. Now it is just a 3x3 matrix.
Vec3f is now Vector3f

I'm compiling moveit_core and it throw out these compile error.

**Comment by jslee02** [comment]
For completion: `Vec3f` is actually `Vector3d`. The scalar type of `Vec3f` was `FCL_REAL`, which is `double`, as `Vector3d` is.

**Pull request merged**
