### PR TITLE
A simple change to documentation to test CI

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
A small PR that adds a single comment to the code. A hacky way to trigger CI on what is essentially master.

Relates to #260 

@sherm1 -- let's see if master fails CI.

---
This change is [Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/261)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
CI failure! The mac fails. Clearly this is a failure in master.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/flexible-collision-library/fcl/261#-:-L6DL3z4ufu26Cbuw7Xx:b-153ze5)*

**Comment by sherm1** [comment]
Yep :cry:

**Comment by sherm1** [comment]
Anyone with a Mac willing to investigate this?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/flexible-collision-library/fcl/261#-:-L6FDhzbJ2rma894LnWs:b5xck4)*

**Comment by SeanCurtis-TRI** [comment]
This has served its purpose; triggered a mac build of the at-time `master` branch illustrating systemic mac failures in unit tests.

**Pull request closed without merging**
