### PR TITLE
Win support

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Visual studio does not support "not".

---
This change is [Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/530)

### CODE REVIEW

**Comment by traversaro** [comment]
Related past PR: https://github.com/flexible-collision-library/fcl/pull/441 .

**Comment by traversaro** [comment]
There are a few other instances of this, see https://github.com/flexible-collision-library/fcl/search?q=not%28FCL_HAVE_OCTOMAP%29&type= . I don't know if it could make sense to fix all of them.

**Comment by Tobias-Fischer** [comment]
Sounds good, I'll fix the other instances tomorrow.

**Comment by Tobias-Fischer** [comment]
Okay, this is ready for review.

**Review by sherm1 — APPROVED** [review]
+@sherm1 for review
:lgtm: thanks @tobias-fischer!

> Reviewed 1 of 1 files at r1, 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/530#-:-MWjqrpKEJN4y6fcNFR6:bc9c1n8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Tobias-Fischer)

**Pull request merged**
