### PR TITLE
fixed bug in meshConservativeAdvancementOrientedNodeCanStop

### PR DESCRIPTION
**Pull request by geoynomous**
"1" is index of "y" coordinate

---
This change is [Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/271)

### CODE REVIEW

**Comment by sherm1** [comment]
:lgtm: -- looks like an obviously good fix to me! Any objections @jslee02 ? That was your TODO there I think.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/flexible-collision-library/fcl/271#-:-L8ZGKLFLXOpqHHhQUT0:b-z9c1bj)*

**Comment by sherm1** [comment]
+@sherm1 +@jslee02 (please lgtm if you're ok with this change)

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/flexible-collision-library/fcl/271#-:-L8ZGWrH5OHJGIVamAA-:b-ydb3er)*

**Comment by jslee02** [comment]
:lgtm: Yeah, I left that note, and this fix looks good to me!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/flexible-collision-library/fcl/271#-:-L8ZOO4U0qmcudJC3TBA:bg9h60a)*

**Comment by sherm1** [comment]
I verified that the CI failures are the usual Mac suspects and unrelated to this PR. Help, Mac people!

**Comment by geoynomous** [comment]
@sherm1 I can test on a Mac - what is the "usual Mac suspects"?

**Comment by mamoll** [comment]
Unit tests pass on my Mac, OS X 10.13.3, Xcode 9.2, Boost 1.66 and libccd 2.0 (the last two installed via MacPorts).

**Comment by sherm1** [comment]
@geoynomous: If you look at the Travis-CI Xcode 7.3 build failures [here](https://travis-ci.org/flexible-collision-library/fcl/builds/358617121?utm_source=github_status&utm_medium=notification) you'll see that the Debug build fails test `test_fcl_capsule_box_1` and the Release build fails that test and also `test_fcl_box_box`. 

We have yet to find a local Mac that reproduces those problems. Our experience here has been like @mamoll reported above -- everything works fine. Our working hypothesis is that there is just something wrong with the Mac compiler being used on Travis but since we can't reproduce the problem it's not very convincing. Issue #265 is tracking this problem. If you are willing to give this a try and report the results in #265, that would be great -- thanks!

**Pull request merged**
