### PR TITLE
Backporting #53 to FCL 0.3

### PR DESCRIPTION
**Pull request by jslee02**
as [requested](https://github.com/flexible-collision-library/fcl/pull/53#issuecomment-234392430).

What I'm not sure is how `FCL_ABI_VERSION` should be updated.

### CODE REVIEW

**Comment by wjwwood** [comment]
@jslee02 I was just trying this locally and I ran into this issue: https://github.com/flexible-collision-library/fcl/issues/132

I looked through our release pipeline and I don't see any patches to address this... It's strange to me that what we're using to release 0.3.2 is compiling, but this branch is not compiling locally...

**Comment by wjwwood** [comment]
Actually, the `0.3.2` tag doesn't compile either :fearful:. I'll keep looking into this issue.

**Comment by wjwwood** [comment]
I figured out my issue. This is a problem anytime you have fcl installed to the same place as one of the dependencies, like octomap, and the installed `config.h` is different from the one you generated while building. I'll open a pr.

**Comment by jslee02** [comment]
Interesting. I've never encountered the issue even though I think I had fcl installed when building another fcl. Anyways, you resolved the mysterious building issue (#132) to me. Thanks!

**Pull request merged**
