### PR TITLE
Populate fcl.pc with the correct installation paths.

### PR DESCRIPTION
**Pull request by mband**
On my Ubuntu 14.04 with CMake 2.8.12 I found the following issue with fcl.pc:
```
# This file was generated by CMake for fcl
prefix=/some/path/projects/fcl_implementation/install_target
exec_prefix=${prefix}
libdir=/some/path/projects/fcl_implementation/install_target/lib
includedir=/some/path/projects/fcl_implementation/install_target/include
```
But the library got placed in `/some/path/projects/fcl_implementation/install_target/lib/x86_64-linux-gnu`and NOT in `/some/path/projects/fcl_implementation/install_target/lib` as specified.

This PR fixes this issue in a similar way as to how it is done in https://github.com/danfis/libccd/blob/master/ccd.pc.in

### CODE REVIEW

**Comment by mband** [comment]
Is there a proper way to trigger a rerun of the Travis CI build? As it failed due to not being able to download the Ubuntu packages...

**Comment by jslee02** [comment]
Without additional commit, it can be triggered by someone has authority. I reran the failed Travis CI builds.

**Comment by scpeters** [comment]
Two builds had spurious failures, and I just re-triggered them.

**Comment by scpeters** [comment]
travis is fixed. +1

**Comment by sherm1** [comment]
:+1: - merge?

**Pull request merged**
