### PR TITLE
Fixing missing assignment in Convex class

### PR DESCRIPTION
**Pull request by k-okada**
BACKPORT of  #74 to fcl-0.3

requested at https://github.com/flexible-collision-library/fcl/pull/74#issuecomment-313268211

### CODE REVIEW

**Comment by rbbg** [comment]
@jslee02 I've been running into this problem with fcl 0.3.3 (Using it with ROS Indigo). Are there any plans to get this released?

**Comment by jslee02** [comment]
@rbbg, [I added the tag for FCL 0.3.4](https://github.com/flexible-collision-library/fcl/releases/tag/0.3.4) that includes this fix. I guess you would like to have debian packages of FCL 0.3.4. I can help updating the debian package at [ppa:fcl-debs/ppa](https://launchpad.net/~fcl-debs/+archive/ubuntu/ppa), but we might need help of @j-rivero for updating ros-indigo-fcl.

**Comment by gavanderhoorn** [comment]
Releasing this would be great. It's a bit of a pain to have to build fcl and moveit and the rest from source just for this 'minor' (in SLOC) fix.

**Comment by gavanderhoorn** [comment]
Just ran into this one again on a different machine.

At least on current Trusty+Indigo this is still an issue.

@j-rivero @jslee02: anything we can do in the community to help you guys get this much needed fix out into a new release?

**Comment by j-rivero** [comment]
> @j-rivero @jslee02: anything we can do in the community to help you guys get this much needed fix out into a new release?

I think it is on plate, sorry for the silence. I've never released fcl as a bloom package into Indigo before. Looking into it now.

**Comment by gavanderhoorn** [comment]
Thanks @j-rivero.

Let me know if there is anything I can do to help.

**Comment by j-rivero** [comment]
https://github.com/ros/rosdistro/pull/15828

@gavanderhoorn If you could please test the package and a software built on top of it as soon as it reach the `shadow` repository, that would great. Thanks!

**Comment by gavanderhoorn** [comment]
@j-rivero: just tested this and it work fine.

Thanks for taking the time to do the release.

**Comment by j-rivero** [comment]
> Thanks for taking the time to do the release.

Thanks you for the work done to fix the problem.

**Comment by gavanderhoorn** [comment]
I didn't do it, it was all @k-okada and @uschwes.

**Pull request merged**
