### PR TITLE
Remove duplicated code between GJKDistance and GJKSignedDistance

### LINKED ISSUE #289: Duplicated code between GJKDistance and GJKSignedDistance
The code in [`GJKSignedDistance`](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1777~L1805) duplicates [`GJKDistance`](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1743~L1772l), except for one slight difference.

The two functions have the same interface. The difference is that `GJKSignedDistance` invokes [`libccd_extension::ccdGJKSignedDist`](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1799) and `GJKDistance` invokes [`libccd_extension::ccdGJKDist2`](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1766). Otherwise, both methods do the same setup and tear down.

These methods should be refactored to call a single, common function (which takes a function pointer to the two different functions).

### PR DESCRIPTION
**Pull request by hongkai-dai**
Resolves #289

---
This change is [Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/292)

### CODE REVIEW

**Comment by sherm1** [comment]
Nice -- :lgtm: with a few BTWs, and pending CI.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1746 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDJQtVg9tGmUOAKUjaZ:-LDJQtVg9tGmUOAKUja_:bwsvnka) ([raw file](https://github.com/flexible-collision-library/fcl/blob/2d6775da421ddfe417c1d518907241fec3477088/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1746)):*
> ```objc
>   typedef S (*type)(const void*, const void*, const ccd_t*, ccd_vec3_t*,
>                     ccd_vec3_t*);
> };
> ```

BTW you don't really need a struct here. Consider:
```c++
template <typename S>
using SignedDistanceFn = 
  std::function<S(const void*, const void*, const ccd_t*, 
                  ccd_vec3_t*, ccd_vec3_t*)>;
```
You could also use the C-style function type declaration -- it's the "using" rather than "typedef" that allows you to templatize.

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1749 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDJPYkUCpknxZgrM6Iy:-LDJPYkUCpknxZgrM6Iz:bl44xyw) ([raw file](https://github.com/flexible-collision-library/fcl/blob/2d6775da421ddfe417c1d518907241fec3477088/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1749)):*
> ```objc
> 
> template <typename S>
> bool GJKDistanceImp(
> ```

BTW more common to use `Impl` as an abbreviation for "implementation". (An "Imp" is a ["small, mischievous devil"](http://tinycastle.wikia.com/wiki/Imp).)

---


*Comments from [Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-:-LDJS8EmE0Ts8c5RPBiX:b-arb263)*

**Comment by SeanCurtis-TRI** [comment]
You have some unique CI issues.

1. Clang seemed to have failed in a meaningless way -- I retriggered those builds to see if they played out differently.
2. Apple is having build errors:
```
In file included from /Users/travis/build/flexible-collision-library/fcl/src/narrowphase/detail/convexity_based_algorithm/gjk_libccd.cpp:38:
/Users/travis/build/flexible-collision-library/fcl/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h:1788:10: error: no matching function for call to 'GJKDistanceImp'
  return internal::GJKDistanceImp(obj1, supp1, obj2, supp2, max_iterations,
         ^~~~~~~~~~~~~~~~~~~~~~~~
/Users/travis/build/flexible-collision-library/fcl/src/narrowphase/detail/convexity_based_algorithm/gjk_libccd.cpp:104:6: note: in instantiation of function template specialization 'fcl::detail::GJKDistance<double>' requested here
bool GJKDistance(
     ^
/Users/travis/build/flexible-collision-library/fcl/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h:1749:6: note: candidate function [with S = double] not viable: no known conversion from 'ccd_real_t (const void *, const void *, const ccd_t *, ccd_vec3_t *, ccd_vec3_t *)' (aka 'float (const void *, const void *, const _ccd_t *, _ccd_vec3_t *, _ccd_vec3_t *)') to 'typename SignedDistanceFn<double>::type' (aka 'double (*)(const void *, const void *, const _ccd_t *, _ccd_vec3_t *, _ccd_vec3_t *)') for 7th argument
bool GJKDistanceImp(
     ^
/Users/travis/build/flexible-collision-library/fcl/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h:1800:10: error: no matching function for call to 'GJKDistanceImp'
  return internal::GJKDistanceImp(
         ^~~~~~~~~~~~~~~~~~~~~~~~
/Users/travis/build/flexible-collision-library/fcl/src/narrowphase/detail/convexity_based_algorithm/gjk_libccd.cpp:116:6: note: in instantiation of function template specialization 'fcl::detail::GJKSignedDistance<double>' requested here
bool GJKSignedDistance(
     ^
/Users/travis/build/flexible-collision-library/fcl/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h:1749:6: note: candidate function [with S = double] not viable: no known conversion from 'ccd_real_t (const void *, const void *, const ccd_t *, ccd_vec3_t *, ccd_vec3_t *)' (aka 'float (const void *, const void *, const _ccd_t *, _ccd_vec3_t *, _ccd_vec3_t *)') to 'typename SignedDistanceFn<double>::type' (aka 'double (*)(const void *, const void *, const _ccd_t *, _ccd_vec3_t *, _ccd_vec3_t *)') for 7th argument
bool GJKDistanceImp(
```

It appears related to the fact that the mac is using a 32-bit build.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1741 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDMYU1a1kDROAru2Dgw:-LDMYU1a1kDROAru2Dgx:b-paqurz) ([raw file](https://github.com/flexible-collision-library/fcl/blob/2d6775da421ddfe417c1d518907241fec3477088/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1741)):*
> ```objc
> }
> 
> namespace internal {
> ```

BTW FCL doesn't have any other instances of `internal` namespace; but it does use a `detail` namespace. I'd suggest swapping.

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1743 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDMXYoz8d8Xp5q9dYk6:-LDMXYoz8d8Xp5q9dYk7:b-xat02v) ([raw file](https://github.com/flexible-collision-library/fcl/blob/2d6775da421ddfe417c1d518907241fec3477088/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1743)):*
> ```objc
> namespace internal {
> template <typename S>
> struct SignedDistanceFn {
> ```

BTW A couple of things:

1. However the function pointer is implemented, it needs to have some documentation. I'd particularly emphasize the semantics of the *returned* value -- should be positive for non-penetrating values and should be negative for penetrating -- although the magnitude of the negative value does *not* have to be meaningful beyond the sign.
2. The name is misleading -- it's not strictly-speaking a "signed distance function"; it's a *distance* function. Whether or not a particular implementation of this function returns a meaningful distance value in penetration is up to the caller. This nuance is what *particulary* calls for documenting this.

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1744 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDM_jHB5YVkrm8aUZR3:-LDM_jHB5YVkrm8aUZR4:blhkggj) ([raw file](https://github.com/flexible-collision-library/fcl/blob/2d6775da421ddfe417c1d518907241fec3477088/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1744)):*
> ```objc
> template <typename S>
> struct SignedDistanceFn {
>   typedef S (*type)(const void*, const void*, const ccd_t*, ccd_vec3_t*,
> ```

BTW Related to your mac CI failure, you probably need to have this return a `ccd_real_t` type instead of an `S`. (Which generally raises the question of "how autodiffable is this, really?")

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1748 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDMYfpa9L_qNqZ_PYYR:-LDMYfpa9L_qNqZ_PYYS:b8ew63j) ([raw file](https://github.com/flexible-collision-library/fcl/blob/2d6775da421ddfe417c1d518907241fec3477088/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1748)):*
> ```objc
> };
> 
> template <typename S>
> ```

BTW As before, I'd ask for docs.  :) Let's leave the code better than when we found it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-:-LDMZhLaA1VfpbJ25Fk0:b-h96h93)*

**Comment by SeanCurtis-TRI** [comment]
Clang builds finished -- original failure *does* seem to have been a transient execution problem. Now you just have the Mac issue.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-:-LDMbkeO-k4iG_QS6f_K:b-ovjohc)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1741 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDMYU1a1kDROAru2Dgw:-LDMnbGJ8c9iYJ36SfaL:bj5tdnk) ([raw file](https://github.com/flexible-collision-library/fcl/blob/2d6775da421ddfe417c1d518907241fec3477088/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1741)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW FCL doesn't have any other instances of `internal` namespace; but it does use a `detail` namespace. I'd suggest swapping.
</blockquote></details>

I tried to swap to `detail` namespace, caused huge amount of compilation errors. I think the reason is that this function is already in `fcl::detail` namespace. Without conflicting with this namespace, I think maybe `internal` namespace is more clear?

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1743 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDMXYoz8d8Xp5q9dYk6:-LDMvMFBEP35bs0Cnp75:b-896fix) ([raw file](https://github.com/flexible-collision-library/fcl/blob/2d6775da421ddfe417c1d518907241fec3477088/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1743)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW A couple of things:

1. However the function pointer is implemented, it needs to have some documentation. I'd particularly emphasize the semantics of the *returned* value -- should be positive for non-penetrating values and should be negative for penetrating -- although the magnitude of the negative value does *not* have to be meaningful beyond the sign.
2. The name is misleading -- it's not strictly-speaking a "signed distance function"; it's a *distance* function. Whether or not a particular implementation of this function returns a meaningful distance value in penetration is up to the caller. This nuance is what *particulary* calls for documenting this.
</blockquote></details>

Done.

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1744 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDM_jHB5YVkrm8aUZR3:-LDMz3vo2l9IPFWmQE22:b-896fix) ([raw file](https://github.com/flexible-collision-library/fcl/blob/2d6775da421ddfe417c1d518907241fec3477088/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1744)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Related to your mac CI failure, you probably need to have this return a `ccd_real_t` type instead of an `S`. (Which generally raises the question of "how autodiffable is this, really?")
</blockquote></details>

Done.

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1746 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDJQtVg9tGmUOAKUjaZ:-LDMvpOJ2P8Z_cp20O-P:b-896fix) ([raw file](https://github.com/flexible-collision-library/fcl/blob/2d6775da421ddfe417c1d518907241fec3477088/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1746)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW you don't really need a struct here. Consider:
```c++
template <typename S>
using SignedDistanceFn = 
  std::function<S(const void*, const void*, const ccd_t*, 
                  ccd_vec3_t*, ccd_vec3_t*)>;
```
You could also use the C-style function type declaration -- it's the "using" rather than "typedef" that allows you to templatize.
</blockquote></details>

Done.

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1748 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDMYfpa9L_qNqZ_PYYR:-LDMvsDfAWRgDyyXCkvn:b-896fix) ([raw file](https://github.com/flexible-collision-library/fcl/blob/2d6775da421ddfe417c1d518907241fec3477088/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1748)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW As before, I'd ask for docs.  :) Let's leave the code better than when we found it.
</blockquote></details>

Done.

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1749 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDJPYkUCpknxZgrM6Iy:-LDMvsjLCPnOeE3FsD46:b-896fix) ([raw file](https://github.com/flexible-collision-library/fcl/blob/2d6775da421ddfe417c1d518907241fec3477088/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1749)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW more common to use `Impl` as an abbreviation for "implementation". (An "Imp" is a ["small, mischievous devil"](http://tinycastle.wikia.com/wiki/Imp).)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/292)*

**Comment by sherm1** [comment]
A few more comments ...

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd.h, line 215 at r2](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDNugAv34n0rvDTgW9r:-LDNugAv34n0rvDTgW9s:b-o4kc0b) ([raw file](https://github.com/flexible-collision-library/fcl/blob/617330691e10f31f586df2b90bf20ad5d007020e/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd.h#L215)):*
> ```objc
>  * @param tolerance The tolerance used in GJK. When the change of distance is
>  * smaller than this tolerance, the algorithm terminates.
>  * @param[out] res The distance between the objects. When the two objects are
> ```

BTW res -> dist

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd.h, line 223 at r2](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDNuF-tAXeXYqTmEBcC:-LDNuF-tAXeXYqTmEBcD:b-s300p1) ([raw file](https://github.com/flexible-collision-library/fcl/blob/617330691e10f31f586df2b90bf20ad5d007020e/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd.h#L223)):*
> ```objc
> template <typename S>
> FCL_EXPORT
> bool GJKDistance(void* obj1, ccd_support_fn supp1,
> ```

BTW what is the `bool` return value for? (Add an `@return` to the doc?) Also for the other signature.

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd.h, line 238 at r2](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDNuk9Q7pXe8QEx4YCq:-LDNuk9Q7pXe8QEx4YCr:b-o4kc0b) ([raw file](https://github.com/flexible-collision-library/fcl/blob/617330691e10f31f586df2b90bf20ad5d007020e/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd.h#L238)):*
> ```objc
>  * @param tolerance The tolerance used in GJK. When the change of distance is
>  * smaller than this tolerance, the algorithm terminates.
>  * @param[out] res The distance between the objects. When the two objects are
> ```

BTW res -> dist

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1760 at r2](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDNt5OHDvmjrzgocxjL:-LDNt5OIAwh6qyxkS2Oj:b-iw04kx) ([raw file](https://github.com/flexible-collision-library/fcl/blob/617330691e10f31f586df2b90bf20ad5d007020e/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1760)):*
> ```objc
>  * @param distance_func The actual function that computes the distance.
>  * Different functions should be passed in, depending on whether the user wants
>  * to compute a signed distance (with penetration depth) of not.
> ```

BTW "of not" -> "or not"

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1761 at r2](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDNuqwd7uPXbDyENVu-:-LDNuqwd7uPXbDyENVu0:boop0gr) ([raw file](https://github.com/flexible-collision-library/fcl/blob/617330691e10f31f586df2b90bf20ad5d007020e/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1761)):*
> ```objc
>  * Different functions should be passed in, depending on whether the user wants
>  * to compute a signed distance (with penetration depth) of not.
>  * @param[out] res The distance between the objects. When the two objects are
> ```

BTW `res` is correct here but did you want to rename it `dist` to match the API?

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1766 at r2](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDNtJtbEyabeIjKIq6v:-LDNtJtc6lC-Lwdboyma:bkztwmh) ([raw file](https://github.com/flexible-collision-library/fcl/blob/617330691e10f31f586df2b90bf20ad5d007020e/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1766)):*
> ```objc
>  * negative distance depends on the implementation.
>  * @param[out] p1 The closest point on object 1 in the world frame.
>  * @param[out] p2 The closest point on object 2 in the world frame.
> ```

FYI I like the `[out]`s here. Since it isn't obvious from the function signature that the input parameters are actually inputs (e.g. `void* obj1` rather than `const void* obj1`) consider marking the other parameters with `[in]`.

(Also for the API methods in gjk_libccd.h.)

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1767 at r2](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDNuzn9-QXkcPX-YMKQ:-LDNuzn9-QXkcPX-YMKR:b-nbtrz7) ([raw file](https://github.com/flexible-collision-library/fcl/blob/617330691e10f31f586df2b90bf20ad5d007020e/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1767)):*
> ```objc
>  * @param[out] p1 The closest point on object 1 in the world frame.
>  * @param[out] p2 The closest point on object 2 in the world frame.
>  */
> ```

BTW return bool needs documentation.

---


*Comments from [Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-:-LDNv5Ah0v5kM9tuAYOk:b-v4hyu7)*

**Comment by sherm1** [comment]
Also looks like it needs a manual merge.

---

Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-:-LDNvFtt3Sf_Gjv54UVB:b-x07p0e)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 2 files reviewed at latest revision, 11 unresolved discussions.

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd.h, line 215 at r2](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDNugAv34n0rvDTgW9r:-LDNytWpCjr9lliPuq5V:b-896fix) ([raw file](https://github.com/flexible-collision-library/fcl/blob/617330691e10f31f586df2b90bf20ad5d007020e/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd.h#L215)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW res -> dist
</blockquote></details>

Done.

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd.h, line 223 at r2](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDNuF-tAXeXYqTmEBcC:-LDNzGA349VZUQdVnOez:b-896fix) ([raw file](https://github.com/flexible-collision-library/fcl/blob/617330691e10f31f586df2b90bf20ad5d007020e/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd.h#L223)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW what is the `bool` return value for? (Add an `@return` to the doc?) Also for the other signature.
</blockquote></details>

Done.

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd.h, line 238 at r2](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDNuk9Q7pXe8QEx4YCq:-LDNzJ98-qoLDhLuvSsF:b-896fix) ([raw file](https://github.com/flexible-collision-library/fcl/blob/617330691e10f31f586df2b90bf20ad5d007020e/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd.h#L238)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW res -> dist
</blockquote></details>

Done.

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1741 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDMYU1a1kDROAru2Dgw:-LDNzKdp9rpjGUU8U_E5:b5naqnb) ([raw file](https://github.com/flexible-collision-library/fcl/blob/2d6775da421ddfe417c1d518907241fec3477088/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1741)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I tried to swap to `detail` namespace, caused huge amount of compilation errors. I think the reason is that this function is already in `fcl::detail` namespace. Without conflicting with this namespace, I think maybe `internal` namespace is more clear?
</blockquote></details>

Removed the namespace.

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1760 at r2](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDNt5OHDvmjrzgocxjL:-LDNzW456Yh5UDanlIsQ:b-896fix) ([raw file](https://github.com/flexible-collision-library/fcl/blob/617330691e10f31f586df2b90bf20ad5d007020e/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1760)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW "of not" -> "or not"
</blockquote></details>

Done.

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1761 at r2](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDNuqwd7uPXbDyENVu-:-LDO-4dI98GnNv4Tnzh1:b317e4d) ([raw file](https://github.com/flexible-collision-library/fcl/blob/617330691e10f31f586df2b90bf20ad5d007020e/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1761)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW `res` is correct here but did you want to rename it `dist` to match the API?
</blockquote></details>

Inside the function it has a local variable also named as`dist`, so I think it is better not to change the variable name.

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1766 at r2](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDNtJtbEyabeIjKIq6v:-LDO--cQ0jDFGmE0PfRB:b-896fix) ([raw file](https://github.com/flexible-collision-library/fcl/blob/617330691e10f31f586df2b90bf20ad5d007020e/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1766)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

FYI I like the `[out]`s here. Since it isn't obvious from the function signature that the input parameters are actually inputs (e.g. `void* obj1` rather than `const void* obj1`) consider marking the other parameters with `[in]`.

(Also for the API methods in gjk_libccd.h.)
</blockquote></details>

Done.

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1767 at r2](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDNuzn9-QXkcPX-YMKQ:-LDO-DtCA_W432lBYBgG:b-896fix) ([raw file](https://github.com/flexible-collision-library/fcl/blob/617330691e10f31f586df2b90bf20ad5d007020e/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1767)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW return bool needs documentation.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/292)*

**Comment by sherm1** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/292)*

**Comment by SeanCurtis-TRI** [comment]
Few last comments

---

Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd.h, line 244 at r3](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDOJYnI9lEN4AGkO-eo:-LDOJYnI9lEN4AGkO-ep:b6d7kc7) ([raw file](https://github.com/flexible-collision-library/fcl/blob/dd1f2bf10c1eca07871c6e4c68b1c63c0173b5f4/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd.h#L244)):*
> ```objc
>  * @param[out] dist The distance between the objects. When the two objects are
>  * not colliding, this is the actual distance, a positive number. When the two
>  * objects are colliding, it is the nagation of the penetration depth, a
> ```

BTW s/nagation/negation

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1710 at r3](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDOJkDl8vUuEeJZYQGz:-LDOJkDl8vUuEeJZYQH-:bc96t0e) ([raw file](https://github.com/flexible-collision-library/fcl/blob/dd1f2bf10c1eca07871c6e4c68b1c63c0173b5f4/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1710)):*
> ```objc
> // number when the object is colliding, though the meaning of that negative
> // number depends on the implementation.
> using DistanceFn = std::function<ccd_real_t(
> ```

BTW missing space `ccd_real_t (`

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1730 at r3](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDOKztQDIHwrmYuEMv-:-LDOKztQDIHwrmYuEMv0:b-1txi0x) ([raw file](https://github.com/flexible-collision-library/fcl/blob/dd1f2bf10c1eca07871c6e4c68b1c63c0173b5f4/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1730)):*
> ```objc
>  * not colliding, this is the actual distance, a positive number. When the two
>  * objects are colliding, it is a negative value. The actual meaning of the
>  * negative distance depends on the implementation.
> ```

BTW I'd say the "actual meaning of the negative distance is defined by `distance_func`.

---

*[include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h, line 1773 at r3](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-LDOM9tt9MJTkApCq9ej:-LDOM9tt9MJTkApCq9ek:b-jv1mlm) ([raw file](https://github.com/flexible-collision-library/fcl/blob/dd1f2bf10c1eca07871c6e4c68b1c63c0173b5f4/include/fcl/narrowphase/detail/convexity_based_algorithm/gjk_libccd-inl.h#L1773)):*
> ```objc
>                  S* res, Vector3<S>* p1, Vector3<S>* p2) {
>   return detail::GJKDistanceImpl(obj1, supp1, obj2, supp2, max_iterations,
>                                   tolerance, libccd_extension::ccdGJKDist2,
> ```

BTW funky indentation

---


*Comments from [Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-:-LDOMIYq8c_o7ytXDHGY:bq6jrch)*

**Comment by SeanCurtis-TRI** [comment]
:LGTM: We'll do one last reality check on the CI when it's done. But should be in a mergeable state.

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-:-LDOV1ytCduKW76AujIw:be2zcik)*

**Comment by SeanCurtis-TRI** [comment]
CI confirmed; ready for merging. @sherm1 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/292#-:-LEAMuFv5yoTnb24vKwl:b-2y4zpe)*

**Pull request merged**
