### PR TITLE
Upstream patches applied during Debian packaging of 0.6.1

### PR DESCRIPTION
**Pull request by jamiesnape**
Relates https://github.com/flexible-collision-library/fcl/issues/474#issuecomment-744530284. Do not squash the three commits.

---
This change is [Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/517)

### CODE REVIEW

**Review by sherm1 — APPROVED** [review]
+@sherm1
Thanks, Jamie! :lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/517#-:-MOn4D5h5LvVIq1OpTaB:bxc4yvq)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jamiesnape)

**Comment by sherm1** [comment]
The fcl repo only allows squash-merge -- @jamiesnape how important is it to keep the commits separate?

**Comment by jamiesnape** [comment]
They are distinct upstream patches, so they should be separate for history and attribution.

**Comment by sherm1** [comment]
OK, temporarily enabled merge commit to preserve the individual commits.

**Pull request merged**
