### PR TITLE
Update EPA test tolerance.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/314)

### CODE REVIEW

**Comment by sherm1** [comment]
*[a discussion](https://reviewable.io/reviews/flexible-collision-library/fcl/314#-LHdDHeu-oEUqfaSR2dT:-LHdtwElBOCLL-n1b8TP:bia33w0) (no related file):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@seancurtis-tri I assumed you meant to unblock this -- apologies if not!

---

**Comment by SeanCurtis-TRI** [comment]
There is still some residue I'm not completely happy with, but I can come to terms with this merge.

**Comment by hongkai-dai** [comment]
I can send another PR to resolve the remaining issues. Shall we discuss this tomorrow when you are at the office?

**Comment by SeanCurtis-TRI** [comment]
Possibly -- at least we can decide if it's even worth doing a follow up. My nitpicks certainly didn't touch the fundamental goodness of this PR.  :)

**Pull request merged**
