### PR TITLE
Fix bug limiting collision between half space and ellipse

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
Essentially, if I asked for a collision between (e, hs) it would work, but (hs, e) would not work. This is because the look up table was missing an entry. This adds the missing entry and a supporting unit test.

---
This change is [Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/520)

### CODE REVIEW

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@sherm1 for review, please.

> *[Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/520#-:-MSFVbN6CJgeIhTKvPUJ:b-3zudpb)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @sherm1)

**Review by sherm1 — APPROVED** [review]
Great -- so nice to have a test!
:lgtm: with a few nits and questions

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/520#-:-MSFgyE_Elz8kj9nVWJG:bl0u7dr)* status: all files reviewed, 4 unresolved discussions (waiting on @SeanCurtis-TRI)

___
*[include/fcl/narrowphase/detail/collision_func_matrix-inl.h, line 762 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/520#-MSFeIF29ETBVG23FU-6:-MSFeIF29ETBVG23FU-7:bi45plv) ([raw file](https://github.com/flexible-collision-library/fcl/blob/d118ad2dd92e8ab767c6a4eaa7fcb9b6a0fd5383/include/fcl/narrowphase/detail/collision_func_matrix-inl.h#L762)):*
> ```objc
>   collision_matrix[GEOM_HALFSPACE][GEOM_PLANE] = &ShapeShapeCollide<Halfspace<S>, Plane<S>, NarrowPhaseSolver>;
>   collision_matrix[GEOM_HALFSPACE][GEOM_HALFSPACE] = &ShapeShapeCollide<Halfspace<S>, Halfspace<S>, NarrowPhaseSolver>;
>   collision_matrix[GEOM_HALFSPACE][GEOM_ELLIPSOID] = &ShapeShapeCollide<Halfspace<S>, Ellipsoid<S>, NarrowPhaseSolver>;
> ```

nit: to be consistent with the other entries, the halfspace/ellipsoid entry should be placed just after halfspace/sphere.
___
*[test/narrowphase/detail/test_collision_func_matrix.cpp, line 4 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/520#-MSFe_H-4b7x4k-xxbu5:-MSFe_H-4b7x4k-xxbu6:b-qsmyqf) ([raw file](https://github.com/flexible-collision-library/fcl/blob/d118ad2dd92e8ab767c6a4eaa7fcb9b6a0fd5383/test/narrowphase/detail/test_collision_func_matrix.cpp#L4)):*
> ```cpp
>  * Software License Agreement (BSD License)
>  *
>  *  Copyright (c) 2018. Toyota Research Institute
> ```

nit 2021
___
*[test/narrowphase/detail/test_collision_func_matrix.cpp, line 90 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/520#-MSFf1msCSV5-4K29Lca:-MSFf1msCSV5-4K29Lcb:b8li7l3) ([raw file](https://github.com/flexible-collision-library/fcl/blob/d118ad2dd92e8ab767c6a4eaa7fcb9b6a0fd5383/test/narrowphase/detail/test_collision_func_matrix.cpp#L90)):*
> ```cpp
> 
> /* The collision function matrix defines the function that can be used to
>  evaluate collision between two CollisionGeometry instances abased on their
> ```

nit abased -> based (or did you mean debased :)
___
*[test/narrowphase/detail/test_collision_func_matrix.cpp, line 91 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/520#-MSFfea73whvEYd6WuRk:-MSFfea73whvEYd6WuRl:bylmwb) ([raw file](https://github.com/flexible-collision-library/fcl/blob/d118ad2dd92e8ab767c6a4eaa7fcb9b6a0fd5383/test/narrowphase/detail/test_collision_func_matrix.cpp#L91)):*
> ```cpp
> /* The collision function matrix defines the function that can be used to
>  evaluate collision between two CollisionGeometry instances abased on their
>  node type. In NodeType, there are nine primitive types, eight BV types, and
> ```

nit NODE_TYPE
___
*[test/narrowphase/detail/test_collision_func_matrix.cpp, line 96 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/520#-MSFgdQ95KZZO6WGlZ5t:-MSFgdQ95KZZO6WGlZ5u:b-qhgt8v) ([raw file](https://github.com/flexible-collision-library/fcl/blob/d118ad2dd92e8ab767c6a4eaa7fcb9b6a0fd5383/test/narrowphase/detail/test_collision_func_matrix.cpp#L96)):*
> ```cpp
> 
>   1 There's a function for all primitive pairs, in both orderings.
>   2 There's a function for each (BV, geometry) combination.
> ```

BTW but _not_ (geometry, BV), right? Is that worth an explicit mention?
___
*[test/narrowphase/detail/test_collision_func_matrix.cpp, line 118 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/520#-MSFg6Xf1VvKXwAMTtAV:-MSFg6Xf1VvKXwAMTtAW:b-3ulkmn) ([raw file](https://github.com/flexible-collision-library/fcl/blob/d118ad2dd92e8ab767c6a4eaa7fcb9b6a0fd5383/test/narrowphase/detail/test_collision_func_matrix.cpp#L118)):*
> ```cpp
>                                 BV_KDOP16, BV_KDOP18, BV_KDOP24};
> 
>   const CollisionFunctionMatrix<GJKSolver_libccd<double>> matrix_struct;
> ```

BTW consider a comment mentioning that the GJKSolver template parameter is a dummy here and not used for anything (assuming that's right).

**Review by SeanCurtis-TRI — COMMENTED** [review]
Hopefully fixed the typos in the octomap-dependent code.

> *[Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/520#-:-MS_-qQR2hH6y3q8v4rZ:bmelsc9)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @sherm1)

___
*[include/fcl/narrowphase/detail/collision_func_matrix-inl.h, line 762 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/520#-MSFeIF29ETBVG23FU-6:-MSZzBpW6kVN2td0pgVB:bb6un1j) ([raw file](https://github.com/flexible-collision-library/fcl/blob/d118ad2dd92e8ab767c6a4eaa7fcb9b6a0fd5383/include/fcl/narrowphase/detail/collision_func_matrix-inl.h#L762)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit: to be consistent with the other entries, the halfspace/ellipsoid entry should be placed just after halfspace/sphere.
</blockquote></details>

Done
___
*[test/narrowphase/detail/test_collision_func_matrix.cpp, line 4 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/520#-MSFe_H-4b7x4k-xxbu5:-MSZzGUw2BtMlewE0oNf:b-o594e5) ([raw file](https://github.com/flexible-collision-library/fcl/blob/d118ad2dd92e8ab767c6a4eaa7fcb9b6a0fd5383/test/narrowphase/detail/test_collision_func_matrix.cpp#L4)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit 2021
</blockquote></details>

Done  I got the *other* year.  :)
___
*[test/narrowphase/detail/test_collision_func_matrix.cpp, line 90 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/520#-MSFf1msCSV5-4K29Lca:-MSZzN5LA8qCkhnBUIDJ:bb6un1j) ([raw file](https://github.com/flexible-collision-library/fcl/blob/d118ad2dd92e8ab767c6a4eaa7fcb9b6a0fd5383/test/narrowphase/detail/test_collision_func_matrix.cpp#L90)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit abased -> based (or did you mean debased :)
</blockquote></details>

Done
___
*[test/narrowphase/detail/test_collision_func_matrix.cpp, line 91 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/520#-MSFfea73whvEYd6WuRk:-MSZzRCTBWBDre4Q38Lj:bb6un1j) ([raw file](https://github.com/flexible-collision-library/fcl/blob/d118ad2dd92e8ab767c6a4eaa7fcb9b6a0fd5383/test/narrowphase/detail/test_collision_func_matrix.cpp#L91)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

nit NODE_TYPE
</blockquote></details>

Done
___
*[test/narrowphase/detail/test_collision_func_matrix.cpp, line 96 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/520#-MSFgdQ95KZZO6WGlZ5t:-MSZzfUQ9h3Tfb3uxfX_:b-8w50q) ([raw file](https://github.com/flexible-collision-library/fcl/blob/d118ad2dd92e8ab767c6a4eaa7fcb9b6a0fd5383/test/narrowphase/detail/test_collision_func_matrix.cpp#L96)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW but _not_ (geometry, BV), right? Is that worth an explicit mention?
</blockquote></details>

Done I've made that explicit.

Although, to be perfectly frank, I can't figure out why. After all, they have both ways for GEOM_OCTREE. Go figure.
___
*[test/narrowphase/detail/test_collision_func_matrix.cpp, line 118 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/520#-MSFg6Xf1VvKXwAMTtAV:-MSZztFwBjjLzOcfpiP7:b-olz4l6) ([raw file](https://github.com/flexible-collision-library/fcl/blob/d118ad2dd92e8ab767c6a4eaa7fcb9b6a0fd5383/test/narrowphase/detail/test_collision_func_matrix.cpp#L118)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

BTW consider a comment mentioning that the GJKSolver template parameter is a dummy here and not used for anything (assuming that's right).
</blockquote></details>

Oops. I actually meant to make this templated on both solvers to determine that they both supported the same matrix. It's why I included headers for both; but then I forgot. Test has been updated.

**Review by sherm1 — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/520)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
