### PR TITLE
Wrong CCD error message minor fix

### PR DESCRIPTION
**Pull request by Sl-Alex**
Wrong CCD version was mentioned in the error message (copy-paste from Eigen3 section above?)

---
This change is [Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/286)

### CODE REVIEW

**Comment by avalenzu** [comment]
:lgtm:. @sl-alex , could you rebase onto master and resolve the conflicts? @seancurtis-tri are these the "usual suspects" for CI failures?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/flexible-collision-library/fcl/286#-:-LASv_uV4Tw4lZnBaWqW:bs3vcwf)*

**Comment by SeanCurtis-TRI** [comment]
Yep. Looks like the usual suspects.

**Comment by SeanCurtis-TRI** [comment]
@sherm1 this exhibits only the usual CI suspects. Ready to merge.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/flexible-collision-library/fcl/286#-:-LAZ7V0c3f_u_K5UqI6T:b-jrsix8)*

**Comment by sherm1** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/flexible-collision-library/fcl/286#-:-LAZCLRU4NB8Zosioovf:bnfp4nl)*

**Pull request merged**
